# Site settings
title: Adam's blog
email: adam@aprice.cf
description: > # this means to ignore newlines until "baseurl:"
  The ramblings of a Linux obsessed IT Technician.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.aprice.cf" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  adamprice56

# Build settings
markdown: kramdown

plugins:
  - jekyll-menus
